# Generated by Django 4.2.4 on 2023-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lingua',
            field=models.CharField(default='portugues', max_length=20),
        ),
    ]
